[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$repositoryRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$assetDirectory = Join-Path $repositoryRoot 'src\EnvironmentComparison\assets'
$imageDataPath = Join-Path $repositoryRoot 'src\EnvironmentComparison\PluginImageData.cs'
[System.IO.Directory]::CreateDirectory($assetDirectory) | Out-Null

function New-ComparisonIcon {
    param(
        [int]$Size,
        [string]$Path
    )

    $bitmap = New-Object System.Drawing.Bitmap $Size, $Size, ([System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
    $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
    $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $scale = $Size / 256.0

    try {
        $background = New-Object System.Drawing.Drawing2D.LinearGradientBrush(
            (New-Object System.Drawing.Rectangle 0, 0, $Size, $Size),
            ([System.Drawing.Color]::FromArgb(51, 65, 85)),
            ([System.Drawing.Color]::FromArgb(37, 99, 235)),
            35.0)
        try {
            $graphics.FillRectangle($background, 0, 0, $Size, $Size)
        }
        finally {
            $background.Dispose()
        }

        $white = New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::FromArgb(246, 248, 252))
        $accent = New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::FromArgb(103, 232, 249))
        $darkPen = New-Object System.Drawing.Pen ([System.Drawing.Color]::FromArgb(30, 41, 59)), ([Math]::Max(1.0, 4.0 * $scale))
        $arrowPen = New-Object System.Drawing.Pen ([System.Drawing.Color]::FromArgb(255, 255, 255)), ([Math]::Max(1.5, 11.0 * $scale))
        $arrowPen.StartCap = [System.Drawing.Drawing2D.LineCap]::Round
        $arrowPen.EndCap = [System.Drawing.Drawing2D.LineCap]::ArrowAnchor

        try {
            function Draw-Database {
                param([double]$X, [System.Drawing.Brush]$Brush)
                $left = [single]($X * $scale)
                $top = [single](57 * $scale)
                $width = [single](74 * $scale)
                $height = [single](124 * $scale)
                $ellipseHeight = [single](25 * $scale)
                $graphics.FillRectangle($Brush, $left, $top + ($ellipseHeight / 2), $width, $height - $ellipseHeight)
                $graphics.FillEllipse($Brush, $left, $top, $width, $ellipseHeight)
                $graphics.FillEllipse($Brush, $left, $top + $height - $ellipseHeight, $width, $ellipseHeight)
                $graphics.DrawEllipse($darkPen, $left, $top, $width, $ellipseHeight)
                $graphics.DrawEllipse($darkPen, $left, $top + [single](44 * $scale), $width, $ellipseHeight)
                $graphics.DrawEllipse($darkPen, $left, $top + [single](88 * $scale), $width, $ellipseHeight)
            }

            Draw-Database -X 30 -Brush $white
            Draw-Database -X 152 -Brush $accent
            $graphics.DrawLine($arrowPen, [single](102 * $scale), [single](92 * $scale), [single](151 * $scale), [single](92 * $scale))
            $graphics.DrawLine($arrowPen, [single](154 * $scale), [single](153 * $scale), [single](105 * $scale), [single](153 * $scale))
        }
        finally {
            $white.Dispose()
            $accent.Dispose()
            $darkPen.Dispose()
            $arrowPen.Dispose()
        }

        $bitmap.Save($Path, [System.Drawing.Imaging.ImageFormat]::Png)
    }
    finally {
        $graphics.Dispose()
        $bitmap.Dispose()
    }
}

New-ComparisonIcon -Size 256 -Path (Join-Path $assetDirectory 'logo.png')
New-ComparisonIcon -Size 80 -Path (Join-Path $assetDirectory 'icon.png')
New-ComparisonIcon -Size 32 -Path (Join-Path $assetDirectory 'icon-32.png')

$small = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes((Join-Path $assetDirectory 'icon-32.png')))
$big = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes((Join-Path $assetDirectory 'icon.png')))
$source = @"
namespace EnvironmentComparison
{
    internal static class PluginImageData
    {
        // Generated by scripts/Generate-Icon-Sizes.ps1.
        public const string Small = "$small";
        public const string Big = "$big";
    }
}
"@
[System.IO.File]::WriteAllText($imageDataPath, $source, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Generated dedicated 256px, 80px, and 32px Environment Comparison images."
Write-Host "Updated $imageDataPath"

